# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PtTools < Formula
  desc "CLI to interact with a Pairtree without knowing the internal structure"
  homepage "https://github.com/UCLALibrary/pt-tools"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt-tools_Darwin_x86_64.zip"
      sha256 "5118813ee8ec09af2070a3ebfdae6b80f3d5d76aee32aff9d9519ccf91b6bc1b"

      def install
        bin.install "pt"
      end
    end
    on_arm do
      url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt-tools_Darwin_arm64.zip"
      sha256 "f78326527170883408f5b7cc76d57a3a61c5712db6cc6348e5c0aee1ea282674"

      def install
        bin.install "pt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt-tools_Linux_x86_64.tar.gz"
        sha256 "c48f2cebf62f2e6a92e921fc78a2ab0f7f3057217646e2911c4cdfecd69f4f06"

        def install
          bin.install "pt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt-tools_Linux_arm64.tar.gz"
        sha256 "6b1ae95de3e3ec5a7aaa67c202ddf3f8b7b5886b02065ab0818508fef189a2e8"

        def install
          bin.install "pt"
        end
      end
    end
  end
end
