# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pt < Formula
  desc "CLI to interact with a Pairtree without knowing the internal structure"
  homepage "https://github.com/UCLALibrary/pt-tools"
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.2/pt-tools_Darwin_x86_64.zip"
      sha256 "aba8ea9b89e1bdd8d4cd3c161227066d66c732a31279b520498fb86c1edf5682"

      def install
        bin.install "pt"
      end
    end
    on_arm do
      url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.2/pt-tools_Darwin_arm64.zip"
      sha256 "402b89810de6867c105e1bc2e9ac324d9cea2fa81e8a4a4d68f10d3c5488ae7e"

      def install
        bin.install "pt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.2/pt-tools_Linux_x86_64.tar.gz"
        sha256 "4300518be534f190c1c2d7033e7d74bebd28057e7261b1c8d130a842a8864128"

        def install
          bin.install "pt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.2/pt-tools_Linux_arm64.tar.gz"
        sha256 "fe7c8e61771757e687bd4b446e6d241d354149f32d9c580879faa7469c5de9c3"

        def install
          bin.install "pt"
        end
      end
    end
  end
end
