# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pt < Formula
  desc "CLI to interact with a Pairtree without knowing the internal structure"
  homepage "https://github.com/UCLALibrary/pt-tools"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt_Darwin_x86_64.zip"
      sha256 "6cccdea48b3745b69000bfe0b5af9bfd4cb1899cab4341901ab6d82df351811a"

      def install
        bin.install "pt"
      end
    end
    on_arm do
      url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt_Darwin_arm64.zip"
      sha256 "daca709dfa5723eb25db97ed1860f955701021869dfd2324696f6d5d0e615730"

      def install
        bin.install "pt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt_Linux_x86_64.tar.gz"
        sha256 "a08c3a5e77121f2bac65c3ef1566264b933362c10051e76af47bcada4f5aae0d"

        def install
          bin.install "pt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt_Linux_arm64.tar.gz"
        sha256 "a93731dc14e77687c4228e6d12b8eed35077edc975210b880087abc61c2c0217"

        def install
          bin.install "pt"
        end
      end
    end
  end
end
