# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pt < Formula
  desc "CLI to interact with a Pairtree without knowing the internal structure"
  homepage "https://github.com/UCLALibrary/pt-tools"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt_Darwin_x86_64.zip"
      sha256 "0816028f8e578364064d1e70265398f977ce717b8b72eddfb333d7d2f65fd51a"

      def install
        bin.install "pt"
      end
    end
    on_arm do
      url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt_Darwin_arm64.zip"
      sha256 "0c4e2e315927197f1e92e8c03fb6ad0a1ff6ea7b626fa90cd292c486b272d3ba"

      def install
        bin.install "pt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt_Linux_x86_64.tar.gz"
        sha256 "a69e52c2950cbdca04ea8ed2408bb92b8d4b0db336dafa0bccdefb74bf5708ce"

        def install
          bin.install "pt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/UCLALibrary/pt-tools/releases/download/v0.0.1/pt_Linux_arm64.tar.gz"
        sha256 "8a60b0e07ea69d811566c15b208d15070e36503bafe49186fad48a8ce32447ee"

        def install
          bin.install "pt"
        end
      end
    end
  end
end
